apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-deployment
  labels:
    app: car
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car
  template:
    metadata:
      labels:
        app: car
    spec:
      containers:
        - name: car
          image: taxi-pos/car
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: car-service
spec:
  selector:
    app: car
  ports:
    - name: car
      protocol: TCP
      port: 3000
      targetPort: 3000
