apiVersion: apps/v1
kind: Deployment
metadata:
  name: emergency-deployment
  labels:
    app: emergency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emergency
  template:
    metadata:
      labels:
        app: emergency
    spec:
      containers:
        - name: emergency
          image: taxi-pos/emergency
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: emergency-service
spec:
  selector:
    app: emergency
  ports:
    - name: emergency
      protocol: TCP
      port: 3000
      targetPort: 3000
