apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
  labels:
    app: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
        - name: middleware
          image: taxi-pos/middleware
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: middleware-service
spec:
  selector:
    app: middleware
  ports:
    - name: middleware
      protocol: TCP
      port: 3000
      targetPort: 3000
