apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-authenticator-deployment
  labels:
    app: otp-authenticator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp-authenticator
  template:
    metadata:
      labels:
        app: otp-authenticator
    spec:
      containers:
        - name: otp-authenticator
          image: taxi-pos/otp-authenticator
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: otp-authenticator-service
spec:
  selector:
    app: otp-authenticator
  ports:
    - name: otp-authenticator
      protocol: TCP
      port: 3000
      targetPort: 3000
